# Generated by Django 4.2.10 on 2025-07-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slidebar_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'inactive')])),
                ('icons', models.CharField(max_length=255)),
            ],
        ),
    ]
