# Generated by Django 4.2.10 on 2025-07-10 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_slidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidebar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slidebar',
            name='role',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slidebar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
