# Generated by Django 4.2.10 on 2025-07-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_slidebar_created_at_slidebar_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidebar',
            name='role',
            field=models.TextField(),
        ),
    ]
