# Generated by Django 4.2.10 on 2025-07-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Slidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slidebar_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'inactive')])),
                ('icons', models.CharField(max_length=255)),
                ('role', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
