# Generated by Django 4.2.10 on 2025-07-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_slidebar',
            name='link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
