# Generated by Django 4.2.10 on 2025-07-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0002_admin_slidebar_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_slidebar',
            name='component',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
