# Generated by Django 4.2.10 on 2025-08-10 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_category_status'),
        ('Admin_Permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='Category.category'),
            preserve_default=False,
        ),
    ]
