# Generated by Django 4.2.10 on 2025-08-10 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_category_status'),
        ('Admin_Permissions', '0002_permissions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='Category.category'),
        ),
    ]
